### ISSUE TITLE
Need some streams guidance

### ISSUE THREAD

**Issue by zeke** [zeke/electron-docs#1]
Hey @maxogden, @mafintosh, and @sindresorhus!

I'm fetching a tarball from GitHub and extracting files out of it. The tarball is saved to disk to make subsequent executions faster:

``` js
  if (exists(tarball)) {
    fs.createReadStream(tarball)
      .pipe(gunzip())
      .pipe(extractor)
      .on('error', function (e) {
        callback(e)
      })
  } else {
    got.stream(tarballUrl)
      .pipe(fs.createWriteStream(tarball))
      .on('end', function () {
        fs.createReadStream(tarball)
          .pipe(gunzip())
          .pipe(extractor)
          .on('error', function (e) {
            callback(e)
          })
      })
  }
```

This is ugly though, and potentially unsafe as noted in the [path-exists](https://github.com/sindresorhus/path-exists) README:

> In particular, checking if a file exists before opening it is an anti-pattern that leaves you vulnerable to race conditions: another process may remove the file between the calls to `fs.exists()` and `fs.open()`. Just open the file and handle the error when it's not there.

However, the idea of setting up a stream to read the file and creating an error handler to detect an `ENOENT` code seems cumbersome to me.

Tell me, O streaming wizards: Is there a more glamorous way to do this?

I think I'm looking for a module that streams files from disk or downloads them if they don't yet exist.

**Comment by mafintosh** [comment]
``` js
var duplexify = require('duplexify')
var pump = require('pump')
var through = require('through2')

pump(createTarStream(), gunzip(), extractor, callback)

function createTarStream () {
  var proxy = duplexify()
  var file = fs.createReadStream(tarball)

  file.on('open', function () {
    file.removeListener('error', onerror)
    proxy.setReadable(file)
  })

  file.on('error', onerror)
  return proxy

  function onerror () {
    var source = got.stream(tarballUrl)
    var copy = through() // just a passthrough
    pump(source, fs.createWriteStream(tarball))
    pump(source, copy)
    proxy.setReadable(copy)
  } 
}
```

**Comment by zeke** [comment]
🙏

**Comment by mafintosh** [comment]
@zeke updated the example to write your cache file as well
